package org.sid.Animalservice;

import org.sid.Animalservice.entities.Animal;
import org.sid.Animalservice.repositories.AnimalRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.UUID;

@SpringBootApplication
public class AnimalServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(AnimalServiceApplication.class, args);
	}

	@Bean
	CommandLineRunner start(AnimalRepository animalRepository){
		return args -> {
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Lion","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Lion_d%27Afrique.jpg/435px-Lion_d%27Afrique.jpg","Living in the grasslands, scrub, and open woodlands of sub-Saharan Africa, the lion is the second largest cat in the world. It is dwarfed slightly by the tiger, which is closely related and has a very similar body typeUnlike other cats, lions are very social animals. They live in groups, called prides, of around 30 lions. A pride consists of up to three males, a dozen related females, and their young. The size of the pride is determined by the availability of food and water. If resources are scarce, the pride becomes smallerPride members keep track of one another by roaring. Both males and females have a very powerful roar that can be heard up to 8 km (5 mi. away.Males and females take on very different roles in the pride. Male lions spend their time guarding their territory and their cubs. They maintain the boundaries of their territory, which can be as large as 260 sq. km (100 sq. mi.), by roaring, marking it with urine, and chasing off intruders. Their thick manes, a unique trait to male lions, protect their necks when they fight with challengers."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Monkey","https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Portrait_of_a_father.jpg/330px-Portrait_of_a_father.jpg","There are currently 264 known monkey species.Monkeys can be divided into two groups, Old World monkeys that live in Africa and Asia, and New World monkeys that live in South America.A baboon is an example of an Old World monkey, while a marmoset is an example of a New World monkey.Apes are not monkeys.Some monkeys live on the ground, while others live in trees.Different monkey species eat a variety of foods, such as fruit, insects, flowers, leaves and reptiles.Most monkeys have tails.Groups of monkeys are known as a ‘tribe’, ‘troop’ or ‘mission’.The Pygmy Marmoset is the smallest type of monkey, with adults weighing between 120 and 140 grams.The Mandrill is the largest type of monkey, with adult males weighing up to 35 kg.Capuchin monkeys are believed to be one of the smartest New World monkey species. They have the ability to use tools, learn new skills and show various signs of self-awareness.Spider monkeys get their name because of their long arms, legs and tail.The monkey is the 9th animal that appears on the Chinese zodiac, appearing as the zodiac sign in 2016."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Owl","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Tyto_alba_tylluan_wen_detail.jpg/435px-Tyto_alba_tylluan_wen_detail.jpg","There are around 200 different owl species.Owls are active at night (nocturnal).A group of owls is called a parliament.Most owls hunt insects, small mammals and other birds.Some owl species hunt fish.Owls have powerful talons (claws) which help them catch and kill prey.Owls have large eyes and a flat face.Owls can turn their heads as much as 270 degrees.Owls are farsighted, meaning they can’t see things close to their eyes clearly.Owls are very quiet in flight compared to other birds of prey.The color of owl’s feathers helps them blend into their environment (camouflage).Barn owls can be recognized by their heart shaped face."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Peacock","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pavo_Real_Venezolano.jpg/330px-Pavo_Real_Venezolano.jpg","Peacocks are large, colorful pheasants (typically blue and green) known for their iridescent tails. These tail feathers, or coverts, spread out in a distinctive train that is more than 60 percent of the bird’s total body length and boast colorful eye markings of blue, gold, red, and other hues. The large train is used in mating rituals and courtship displays. It can be arched into a magnificent fan that reaches across the bird's back and touches the ground on either side. Females are believed to choose their mates according to the size, color, and quality of these outrageous feather trains.Peacocks are ground-feeders that eat insects, plants, and small creatures. There are two familiar peacock species. The blue peacock lives in India and Sri Lanka, while the green peacock is found in Java and Myanmar (Burma). A more distinct and little-known species, the Congo peacock, inhabits African rain forests.Peafowl such as the blue peacock have been admired by humans and kept as pets for thousands of years. Selective breeding has created some unusual color combinations, but wild birds are themselves bursting with vibrant hues. They can be testy and do not mix well with other domestic birds."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Spider","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Australian_orb_weaver_spinning_web.jpg/330px-Australian_orb_weaver_spinning_web.jpg","Spiders are arachnids, not insects.Other members of the arachnid family include scorpions, mites, ticks and harvestmen.Spiders have 8 legs while insects have 6.Spiders don’t have antennae while insects do.Spiders are found on every continent of the world except Antarctica.There are around 40000 different species of spider.Most spiders make silk which they use to create spider webs and capture prey.Abandoned spider webs are called cobwebs.Most spiders are harmless to humans but a few spider species, such as the black widow, can bite humans and inject venom. Deaths from spider bites are rare however.An abnormal fear of spiders is called ‘arachnophobia’.Tarantulas are large and often hairy spiders, the biggest species have been known to kill mice, lizards and birds.Most tarantula species pose no threat to humans.The largest specie of tarantula is the Goliath Birdeater.Giant Huntsman spiders have leg-spans of around 30cm (12 in)."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Tortoise","https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Astrochelis_radiata1.jpg/435px-Astrochelis_radiata1.jpg","description\":\"A tortoise's shell is made up of 60 different bones all connected to each other The top of a tortoise's shell is called a “carapace” The underside of the shell is called a “plastron” The carapace and the plastron of a tortoises shell is connected by what is known as a bridge Tortoises can retract their heads and all their limbs including their tails into their shells when they feel threatened or attacked by predators Tortoises have extremely strong mouths but no teeth instead they have horny type beaks Tortoises have good all round vision and a very good sense of smell Tortoises are cold-blooded – they draw heat from their environment and are more active during the day than at night Tortoises can live a very long time, some to the ripe old age of 150. However, the average age a tortoise can live to ranges from 90 to 150 years Tortoises are what is known as herbivores, they eat grass, ferns, flowers, tree leaves and fruit Female tortoises are usually larger than their male counterparts Females dig burrows in which they can lay up anything from 1 to 30 eggs A male tortoise has a longer tail than that of a female, which is one way of sexing them When baby tortoises break out of their shells they are called hatchlingsTortoise eggs incubate between 90 to 120 days to hatch out Tortoises hibernate in the winter time and before they do, they starve themselves so their stomachs are empty ready for hibernation"));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Zebra","https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Common_zebra_1.jpg/1200px-Common_zebra_1.jpg","Zebra are part of the equidae family along with horse and donkeys.Every zebra has a unique pattern of black and white stripes.There are a number of different theories which attempt to explain zebra’s unique stripes with most relating to camouflage.Wild zebras live in Africa.Common plain zebras have tails around half a metre in length (18 inches).Zebra crossings (pedestrian crossings) are named after the black and white stripes of zebras.Zebras run from side to side to being chased by a predator.Zebras have excellent eyesight and hearing.Zebras stand up while sleeping.Zebras eat mostly grass.The ears of a zebra show its mood.A zebra named Marty starred in the 2005 animated film Madagascar."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Tiger","https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/2012_Suedchinesischer_Tiger.JPG/330px-2012_Suedchinesischer_Tiger.JPG","The tiger (Panthera tigris) is the largest living cat species and a member of the genus Panthera. It is most recognisable for its dark vertical stripes on orange fur with a white underside. An apex predator, it primarily preys on ungulates, such as deer and wild boar. It is territorial and generally a solitary but social predator, requiring large contiguous areas of habitat to support its requirements for prey and rearing of its offspring. Tiger cubs stay with their mother for about two years and then become independent, leaving their mother's home range to establish their own."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Panda","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/330px-Grosser_Panda.JPG","The giant panda (Ailuropoda melanoleuca, sometimes panda bear or simply panda), is a bear species endemic to China. It is characterised by its bold black-and-white coat and rotund body. The name \"giant panda\" is sometimes used to distinguish it from the red panda, a neighboring musteloid. Though it belongs to the order Carnivora, the giant panda is a folivore, with bamboo shoots and leaves making up more than 99% of its diet. Giant pandas in the wild occasionally eat other grasses, wild tubers, or even meat in the form of birds, rodents, or carrion. In captivity, they may receive honey, eggs, fish, yams, shrub leaves, oranges, or bananas along with specially prepared food."));
			animalRepository.save(new Animal(UUID.randomUUID().toString(),"Wolf","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kolm%C3%A5rden_Wolf.jpg/330px-Kolm%C3%A5rden_Wolf.jpg","The wolf , also known as the gray wolf or grey wolf, is a large canine native to Eurasia and North America. More than thirty subspecies of Canis lupus have been recognized, and gray wolves, as popularly understood, comprise wild subspecies. The wolf is the largest extant member of the family Canidae. It is also distinguished from other Canis species by its less pointed ears and muzzle, as well as a shorter torso and a longer tail. The wolf is nonetheless related closely enough to smaller Canis species, such as the coyote and the golden jackal, to produce fertile hybrids with them. The banded fur of a wolf is usually mottled white, brown, gray, and black, although subspecies in the arctic region may be nearly all white."));

		};
	}

}
